name: crypto_buddy
description: CryptoBuddy provides current data of popular digital currencies
  and allows users to build their own portfolios.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.2
  coingecko_api: ^1.1.1+1
  provider: ^6.0.5
  mockito: ^5.4.3
  fl_chart: ^0.65.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4

flutter:
  uses-material-design: true
  assets:
    - img/

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "img/new_logo.png"
  adaptive_icon_foreground: "img/new_logo.png"
  image_path: "img/new_logo.png"
  min_sdk_android: 16 # android min sdk:16, default: 21
  windows:
    generate: true
    icon_size: 150 # min:48, max:256, default: 48
